### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by benbitrise** [LexBitrise/bitrise-step-log-hardware-utilization#11]
The step needs an icon

**Comment by LexBitrise** [comment]
Solved, created an icon, could be revised if needed

![CPU:RAM utilization](https://github.com/LexBitrise/bitrise-step-log-hardware-utilization/assets/120204218/71e56c5e-f310-4b2c-becf-13e89693e52d)

**Comment by benbitrise** [comment]
wow nice!
